# -------------------------------------------------------------------------------------
#
#
#    Script for running LDSC and MAGMA on snRNA-seq data
#
#
# -------------------------------------------------------------------------------------

# ---------  SET SMK PARAMS  ----------
configfile: "../config/config.yaml"

#include: "rules/9_snRNAseq_rare_variants.smk"
#include: "rules/8_snRNAseq_plot_MAGMA_and_LDSR.smk"
#include: "rules/7_snRNAseq_LDSR_top1000.smk"
#include: "rules/6_snRNAseq_LDSR_dwnSmpl.smk"
#include: "rules/5_snRNAseq_LDSR.smk"
#include: "rules/4_snRNAseq_MAGMA.smk"
include: "rules/3_snRNAseq_get_and_munge_GWAS.smk"
#include: "rules/2_snRNAseq_prep_enrich_files.smk"
#include: "rules/1_snRNAseq_get_and_prep_herring_data.smk"
#include: "rules/snRNAseq_prep_enrich_files_new.smk"
#include: "rules/snRNAseq_MAGMA.smk"
#include: "rules/snRNAseq_LDSR.smk"
#include: "rules/snRNAseq_LDSR_dwnSmpl.smk"

# -------------  RULES  ---------------
rule all:
    input:
#        expand("../results/figures/wilcoxon_herring_dwnSmpl_lvl{LEVEL}_plot.jpeg", LEVEL = config['LEVEL']),#rules9
#        expand("../results/figures/wilcoxon_herring_lvl{LEVEL}_plot.jpeg", LEVEL = config['LEVEL']),#rules9
#        expand("../results/rare_variants/rare_variants_analysis_{project}.done", project = config['project']),#rules9
#        expand("../results/LDSR_part_herit/baseline_v1.2/herring/top1000_genes/snRNAseq_LDSR_{GWAS}_baseline.v1.2_summary.tsv", GWAS = config['GWAS']),#rules7 - herring_top1000
#        expand("../results/LDSR_part_herit/baseline_v1.2/herring_dwnSmpl/snRNAseq_LDSR_{GWAS}_baseline.v1.2_summary.tsv", GWAS = config['GWAS']),#rules6 - herring_dwnSmpl
#        expand("../results/LDSR_part_herit/baseline_v1.2/herring/snRNAseq_LDSR_{GWAS}_baseline.v1.2_summary.tsv", GWAS = config['GWAS']),#rules5 - herring
#        expand("../results/magma/snRNAseq_{GWAS}.herring.top1000.lvl{LEVEL}.magma.35UP_10DOWN.gsa.out", GWAS = config['GWAS'], LEVEL = config['LEVEL']),#rules4 - herring_top1000
#        expand("../results/magma/snRNAseq_{GWAS}.herring_dwnSmpl.lvl{LEVEL}.magma.35UP_10DOWN.gsa.out", GWAS = config['GWAS'], LEVEL = config['LEVEL']),#rules4 - herring_dwnSmpl
#        expand("../results/magma/snRNAseq_{GWAS}.herring.lvl{LEVEL}.magma.35UP_10DOWN.gsa.out", GWAS = config['GWAS'], LEVEL = config['LEVEL']),#rules4 - herring
        expand("../results/GWAS_for_ldsc/{GWAS}_hg19_ldsc_ready.sumstats.gz", GWAS = config['GWAS']),#rules3
#        "../results/GWAS_for_MAGMA/SCZ_hg19_magma_ready.tsv",#rules3
#        expand("../results/gene_lists/prep_enrichment_file_{project}.done", project = config['project']),#rules2
#        "../results/R_objects/seurat_herring.rds",#rules1
#        "../resources/raw_data/herring_2022/data_for_R/herring_counts_geneMeta.csv",#rules 1
#
#
#        expand("../results/magma/snRNAseq_{GWAS}.{project}.{norm}.magma.35UP_10DOWN.gsa.out", GWAS = config['GWAS'], project = config['project'], norm = config['norm']),
#        expand("../results/magma/snRNAseq_{GWAS}.top1000.lvl_{LEVEL}.magma.35UP_10DOWN.gsa.out", GWAS = config['GWAS'], LEVEL = config['LEVEL']),
#        expand("../results/LDSR_part_herit/baseline_v1.2/herring/snRNAseq_LDSR_{GWAS}_baseline.v1.2_summary.tsv", GWAS = config['GWAS']),
#        expand("../results/LDSR_part_herit/baseline_v1.2/herring_dwnSmpl_lvl2/{norm}/snRNAseq_LDSR_{GWAS}_baseline.v1.2_summary.tsv", norm = config['norm'], GWAS = config['GWAS']),
#        expand("../results/LDSR_part_herit/baseline_v1.2/herring_top1000/snRNAseq_LDSR_{GWAS}_baseline.v1.2_summary.tsv", GWAS = config['GWAS'])
