CELL_TYPE:
    Astro.lvl1.100UP_100DOWN:
    CGE_dev.lvl1.100UP_100DOWN:
    ID2.lvl1.100UP_100DOWN:
    L2-3_CUX2.lvl1.100UP_100DOWN:
    L4_RORB.lvl1.100UP_100DOWN:
    L5-6_THEMIS.lvl1.100UP_100DOWN:
    L5-6_TLE4.lvl1.100UP_100DOWN:
    LAMP5_NOS1.lvl1.100UP_100DOWN:
    MGE_dev.lvl1.100UP_100DOWN:
    Micro.lvl1.100UP_100DOWN:
    Oligo.lvl1.100UP_100DOWN:
    OPC.lvl1.100UP_100DOWN:
    PN_dev.lvl1.100UP_100DOWN:
    Poor-Quality.lvl1.100UP_100DOWN:
    PV.lvl1.100UP_100DOWN:
    PV_SCUBE3.lvl1.100UP_100DOWN:
    SST.lvl1.100UP_100DOWN:
    Vas.lvl1.100UP_100DOWN:
    VIP.lvl1.100UP_100DOWN:
    Astro_dev-1.lvl2.100UP_100DOWN:
    Astro_dev-2.lvl2.100UP_100DOWN:
    Astro_dev-3.lvl2.100UP_100DOWN:
    Astro_dev-4.lvl2.100UP_100DOWN:
    Astro_dev-5.lvl2.100UP_100DOWN:
    Astro_GFAP.lvl2.100UP_100DOWN:
    Astro_SLC1A2_dev.lvl2.100UP_100DOWN:
    Astro_SLC1A2.lvl2.100UP_100DOWN:
    BKGR_NRGN.lvl2.100UP_100DOWN:
    CCK_RELN.lvl2.100UP_100DOWN:
    CCK_SORCS1.lvl2.100UP_100DOWN:
    CCK_SYT6.lvl2.100UP_100DOWN:
    CGE_dev.lvl2.100UP_100DOWN:
    ID2_CSMD1.lvl2.100UP_100DOWN:
    ID2_dev.lvl2.100UP_100DOWN:
    L2-3_CUX2_dev-1.lvl2.100UP_100DOWN:
    L2-3_CUX2_dev-2.lvl2.100UP_100DOWN:
    L2-3_CUX2_dev-3.lvl2.100UP_100DOWN:
    L2-3_CUX2_dev-4.lvl2.100UP_100DOWN:
    L2-3_CUX2_dev-5.lvl2.100UP_100DOWN:
    L2-3_CUX2_dev-6.lvl2.100UP_100DOWN:
    L2-3_CUX2_dev-fetal.lvl2.100UP_100DOWN:
    L2_CUX2_LAMP5_dev.lvl2.100UP_100DOWN:
    L2_CUX2_LAMP5.lvl2.100UP_100DOWN:
    L3_CUX2_PRSS12.lvl2.100UP_100DOWN:
    L4_RORB_dev-1.lvl2.100UP_100DOWN:
    L4_RORB_dev-2.lvl2.100UP_100DOWN:
    L4_RORB_dev-fetal.lvl2.100UP_100DOWN:
    L4_RORB_LRRK1.lvl2.100UP_100DOWN:
    L4_RORB_MET.lvl2.100UP_100DOWN:
    L4_RORB_MME.lvl2.100UP_100DOWN:
    L5-6_THEMIS_CNR1.lvl2.100UP_100DOWN:
    L5-6_THEMIS_dev-1.lvl2.100UP_100DOWN:
    L5-6_THEMIS_dev-2.lvl2.100UP_100DOWN:
    L5-6_THEMIS_NTNG2.lvl2.100UP_100DOWN:
    L5-6_TLE4_dev.lvl2.100UP_100DOWN:
    L5-6_TLE4_HTR2C.lvl2.100UP_100DOWN:
    L5-6_TLE4_SCUBE1.lvl2.100UP_100DOWN:
    L5-6_TLE4_SORCS1.lvl2.100UP_100DOWN:
    LAMP5_CCK.lvl2.100UP_100DOWN:
    LAMP5_NDNF.lvl2.100UP_100DOWN:
    LAMP5_NOS1.lvl2.100UP_100DOWN:
    MGE_dev-1.lvl2.100UP_100DOWN:
    MGE_dev-2.lvl2.100UP_100DOWN:
    Micro.lvl2.100UP_100DOWN:
    Micro_out.lvl2.100UP_100DOWN:
    Oligo-1.lvl2.100UP_100DOWN:
    Oligo-2.lvl2.100UP_100DOWN:
    Oligo-3.lvl2.100UP_100DOWN:
    Oligo-4.lvl2.100UP_100DOWN:
    Oligo-5.lvl2.100UP_100DOWN:
    Oligo_mat.lvl2.100UP_100DOWN:
    OPC_dev.lvl2.100UP_100DOWN:
    OPC.lvl2.100UP_100DOWN:
    OPC_MBP.lvl2.100UP_100DOWN:
    PN_dev.lvl2.100UP_100DOWN:
    PV_dev.lvl2.100UP_100DOWN:
    PV_SCUBE3_dev.lvl2.100UP_100DOWN:
    PV_SCUBE3.lvl2.100UP_100DOWN:
    PV_SST.lvl2.100UP_100DOWN:
    PV_SULF1_dev.lvl2.100UP_100DOWN:
    PV_SULF1.lvl2.100UP_100DOWN:
    PV_WFDC2.lvl2.100UP_100DOWN:
    SST_ADGRG6_dev.lvl2.100UP_100DOWN:
    SST_ADGRG6.lvl2.100UP_100DOWN:
    SST_B3GAT2.lvl2.100UP_100DOWN:
    SST_BRINP3.lvl2.100UP_100DOWN:
    SST_CALB1_dev.lvl2.100UP_100DOWN:
    SST_CALB1.lvl2.100UP_100DOWN:
    SST_NPY.lvl2.100UP_100DOWN:
    SST_STK32A.lvl2.100UP_100DOWN:
    SST_TH.lvl2.100UP_100DOWN:
    Vas_CLDN5.lvl2.100UP_100DOWN:
    Vas_PDGFRB.lvl2.100UP_100DOWN:
    Vas_TBX18.lvl2.100UP_100DOWN:
    VIP_ABI3BP.lvl2.100UP_100DOWN:
    VIP_ADAMTSL1.lvl2.100UP_100DOWN:
    VIP_CHRM2.lvl2.100UP_100DOWN:
    VIP_CRH.lvl2.100UP_100DOWN:
    VIP_dev.lvl2.100UP_100DOWN:
    VIP_DPP6.lvl2.100UP_100DOWN:
    VIP_HS3ST3A1.lvl2.100UP_100DOWN:
    VIP_KIRREL3.lvl2.100UP_100DOWN:
    VIP_PCDH20.lvl2.100UP_100DOWN:

GWAS:
    SCZ:
    HEIGHT:

LEVEL:
    1:
    2:

project:
    herring:
#    herring_dwnSmpl_lvl1:
#    herring_dwnSmpl_lvl2:
