CELL_TYPE:
    Astro_dev-1.lvl2.100UP_100DOWN:
    Astro_dev-2.lvl2.100UP_100DOWN:
    Astro_dev-3.lvl2.100UP_100DOWN:
    Astro_dev-4.lvl2.100UP_100DOWN:
    Astro_dev-5.lvl2.100UP_100DOWN:
    Astro_GFAP.lvl2.100UP_100DOWN:
    Astro_SLC1A2_dev.lvl2.100UP_100DOWN:
    Astro_SLC1A2.lvl2.100UP_100DOWN:
    BKGR_NRGN.lvl2.100UP_100DOWN:
    CCK_RELN.lvl2.100UP_100DOWN:
    CCK_SORCS1.lvl2.100UP_100DOWN:
    CCK_SYT6.lvl2.100UP_100DOWN:
    CGE_dev.lvl2.100UP_100DOWN:
    ID2_CSMD1.lvl2.100UP_100DOWN:
    ID2_dev.lvl2.100UP_100DOWN:
    L2-3_CUX2_dev-1.lvl2.100UP_100DOWN:
    L2-3_CUX2_dev-2.lvl2.100UP_100DOWN:
    L2-3_CUX2_dev-3.lvl2.100UP_100DOWN:
    L2-3_CUX2_dev-4.lvl2.100UP_100DOWN:
    L2-3_CUX2_dev-5.lvl2.100UP_100DOWN:
    L2-3_CUX2_dev-6.lvl2.100UP_100DOWN:
    L2-3_CUX2_dev-fetal.lvl2.100UP_100DOWN:
    L2_CUX2_LAMP5_dev.lvl2.100UP_100DOWN:
    L2_CUX2_LAMP5.lvl2.100UP_100DOWN:
    L3_CUX2_PRSS12.lvl2.100UP_100DOWN:
    L4_RORB_dev-1.lvl2.100UP_100DOWN:
    L4_RORB_dev-2.lvl2.100UP_100DOWN:
    L4_RORB_dev-fetal.lvl2.100UP_100DOWN:
    L4_RORB_LRRK1.lvl2.100UP_100DOWN:
    L4_RORB_MET.lvl2.100UP_100DOWN:
    L4_RORB_MME.lvl2.100UP_100DOWN:
    L5-6_THEMIS_CNR1.lvl2.100UP_100DOWN:
    L5-6_THEMIS_dev-1.lvl2.100UP_100DOWN:
    L5-6_THEMIS_dev-2.lvl2.100UP_100DOWN:
    L5-6_THEMIS_NTNG2.lvl2.100UP_100DOWN:
    L5-6_TLE4_dev.lvl2.100UP_100DOWN:
    L5-6_TLE4_HTR2C.lvl2.100UP_100DOWN:
    L5-6_TLE4_SCUBE1.lvl2.100UP_100DOWN:
    L5-6_TLE4_SORCS1.lvl2.100UP_100DOWN:
    LAMP5_CCK.lvl2.100UP_100DOWN:
    LAMP5_NDNF.lvl2.100UP_100DOWN:
    LAMP5_NOS1.lvl2.100UP_100DOWN:
    MGE_dev-1.lvl2.100UP_100DOWN:
    MGE_dev-2.lvl2.100UP_100DOWN:
    Micro.lvl2.100UP_100DOWN:
    Micro_out.lvl2.100UP_100DOWN:
    Oligo-1.lvl2.100UP_100DOWN:
    Oligo-2.lvl2.100UP_100DOWN:
    Oligo-3.lvl2.100UP_100DOWN:
    Oligo-4.lvl2.100UP_100DOWN:
    Oligo-5.lvl2.100UP_100DOWN:
    Oligo_mat.lvl2.100UP_100DOWN:
    OPC_dev.lvl2.100UP_100DOWN:
    OPC.lvl2.100UP_100DOWN:
    OPC_MBP.lvl2.100UP_100DOWN:
    PN_dev.lvl2.100UP_100DOWN:
    PV_dev.lvl2.100UP_100DOWN:
    PV_SCUBE3_dev.lvl2.100UP_100DOWN:
    PV_SCUBE3.lvl2.100UP_100DOWN:
    PV_SST.lvl2.100UP_100DOWN:
    PV_SULF1_dev.lvl2.100UP_100DOWN:
    PV_SULF1.lvl2.100UP_100DOWN:
    PV_WFDC2.lvl2.100UP_100DOWN:
    SST_ADGRG6_dev.lvl2.100UP_100DOWN:
    SST_ADGRG6.lvl2.100UP_100DOWN:
    SST_B3GAT2.lvl2.100UP_100DOWN:
    SST_BRINP3.lvl2.100UP_100DOWN:
    SST_CALB1_dev.lvl2.100UP_100DOWN:
    SST_CALB1.lvl2.100UP_100DOWN:
    SST_NPY.lvl2.100UP_100DOWN:
    SST_STK32A.lvl2.100UP_100DOWN:
    SST_TH.lvl2.100UP_100DOWN:
    Vas_CLDN5.lvl2.100UP_100DOWN:
    Vas_PDGFRB.lvl2.100UP_100DOWN:
    Vas_TBX18.lvl2.100UP_100DOWN:
    VIP_ABI3BP.lvl2.100UP_100DOWN:
    VIP_ADAMTSL1.lvl2.100UP_100DOWN:
    VIP_CHRM2.lvl2.100UP_100DOWN:
    VIP_CRH.lvl2.100UP_100DOWN:
    VIP_dev.lvl2.100UP_100DOWN:
    VIP_DPP6.lvl2.100UP_100DOWN:
    VIP_HS3ST3A1.lvl2.100UP_100DOWN:
    VIP_KIRREL3.lvl2.100UP_100DOWN:
    VIP_PCDH20.lvl2.100UP_100DOWN:

GWAS:
    SCZ_EUR_ONLY: https://figshare.com/ndownloader/files/34517828
#    HEIGHT: https://portals.broadinstitute.org/collaboration/giant/images/6/63/Meta-analysis_Wood_et_al%2BUKBiobank_2018.txt.gz
#    ASD: https://figshare.com/ndownloader/files/28169292
#    ADHD: https://figshare.com/ndownloader/files/40036684
#    MDD: /nfs/neurocluster/databank/c.mdnra_shared/summaryqc/restricted/wray-ripke-mattheisen-2017-mdd-23me/wray-ripke-mattheisen-2017-mdd-23me-summaryqc.tsv.gz
#    BPD: https://figshare.com/ndownloader/files/26603681
#    NEUROTICISM: ../results/GWAS/neuroticism.gwas.full.txt.gz
#    BMI: https://portals.broadinstitute.org/collaboration/giant/images/c/c8/Meta-analysis_Locke_et_al%2BUKBiobank_2018_UPDATED.txt.gz


LEVEL:
    2:

project:
    herring:

CELL_TYPE_GO_TERM:
    L4_RORB_LRRK1-GO.0050877.lvl2.100UP_100DOWN:
    L4_RORB_LRRK1-GO.0055085.lvl2.100UP_100DOWN:
    L4_RORB_LRRK1-GO.0060078.lvl2.100UP_100DOWN:
    L4_RORB_LRRK1-GO.0071805.lvl2.100UP_100DOWN:
    L4_RORB_LRRK1-GO.0098660.lvl2.100UP_100DOWN:
    L4_RORB_LRRK1-GO.0003008.lvl2.100UP_100DOWN:
    L4_RORB_LRRK1-GO.0006811.lvl2.100UP_100DOWN:
    L4_RORB_LRRK1-GO.0006813.lvl2.100UP_100DOWN:
    L4_RORB_LRRK1-GO.0006836.lvl2.100UP_100DOWN:
    L4_RORB_LRRK1-GO.0007186.lvl2.100UP_100DOWN:
    L4_RORB_LRRK1-GO.0007267.lvl2.100UP_100DOWN:
    L4_RORB_LRRK1-GO.0007268.lvl2.100UP_100DOWN:
    L4_RORB_LRRK1-GO.0007270.lvl2.100UP_100DOWN:
    L4_RORB_LRRK1-GO.0007399.lvl2.100UP_100DOWN:
    L4_RORB_LRRK1-GO.0019226.lvl2.100UP_100DOWN:
    L4_RORB_LRRK1-GO.0042391.lvl2.100UP_100DOWN:
    L4_RORB_LRRK1-GO.0043269.lvl2.100UP_100DOWN:
    L4_RORB_LRRK1-GO.0046903.lvl2.100UP_100DOWN:
    L4_RORB_LRRK1-GO.0050804.lvl2.100UP_100DOWN:
    L4_RORB_LRRK1-GO.0050808.lvl2.100UP_100DOWN:
